config/routes.rb
Rails.application.routes.draw do
  get '/products/:id', to: 'products#show'
  get '/products', to:'products#index'
  get 'orders/show'
  get 'orders/index'

  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/landing_page'
  resources :products
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#landing_page'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  def self.search(search_term)
    Product.where("name LIKE ?", "%#{search_term}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/helpers/simple_page_helper.rb
module SimplePageHelper
end

app/controllers/oders_controller.rb
class OdersController < ApplicationController
  def index
    @orders = Order.includes(:product).all

  end

  def show
    @order = Order.find(params[:id])
  end

  def new

  end

  def create

  end

  def destroy

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.includes(:product).all

  end

  def show
    @order = Order.find(params[:id])
  end

  def new

  end

  def create

  end

  def destroy

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @product = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController


  def landing_page
    # @featured_product = Product.first
    @products = Product.limit(3)
  end
end

app/helpers/oders_helper.rb
module OdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yourapp</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <%= link_to "Home", root_path %>
      <%= link_to "About", simple_pages_about_path %>
      <%= link_to "Products",products_path %>
      <%= link_to "Contact", simple_pages_contact_path %>
      <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
      <%= form.label :q, 'Search for:' %>
      <%= form.text_field :q, id: 'q', value: params[:q] %>
      <%= form.submit 'Search' %>
      <% end %>
    </div>
  </nav>
    <%= yield %>

    <footer>
      &copy; 2018 Bike Berlin
    </footer>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

<div class="row">
  <% @orders.each do |order| %>
    <div class="col-sm">
      <h1>
        Order # <%= order.id %>:
        <%= link_to order.product.name, order %>
      </h1>
      <p><%= order.product.description %></p>
      <strong>$ <%= order.product.price %></strong>
    </div><!-- /col -->
  <% end %>
</div>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

<div class="container">
  <h2>Order Information</h2>
  <strong>Order ID: </strong><%= @order.id %>
  <strong>Product Name: </strong><%= @order.product.name %>
  <strong>Product Price: </strong><%= number_to_currency(@order.product.price/100.to_f) %>
  <strong>Total Price: </strong><%= number_to_currency(@order.total/100.to_f) %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %><br>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :colour %><br>
    <%= form.text_field :colour %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<% @products.each do |product| %>
  <div class="col-sm-4">
    <%= image_tag(product.image_url, class: "img-fluid") unless product.image_url.nil? %>
    <a href="#"><h1><td><%= product.name %></td></h1></a>
    <p><td><%= product.description %></td></p>
    <p><td><%= product.colour %></td></p>
    <p><td><%= product.price %></td></p>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>



<div class="container-fluid">
  <div class="row">
    <%= render @products %>
  </div>
</div>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/simple_pages/about.html.erb
<div class="about">
  <h1>All about bikes</h1>
  <!-- <p>Find me in app/views/simple_pages/about.html.erb</p> -->
  <p>This bike store is based in Munich and we can diliver to any part of Germany.</p>
  <p>You can rent it, sell it or buy.</p>
  <p>There is no compromise in price and quality.</p>
  <p>Your comfort our priority.</p>


  <%= image_tag("rental_bike2.jpg", class: "img-fluid") %>
  <figcaption> City Bike</figcaption>



  <%= image_tag("rental_bike1.jpg", class: "img-fluid") %>
  <figcaption> City Bike</figcaption>

</div>

app/views/simple_pages/contact.html.erb
<h1>Munich Online Bike Shop</h1>
<!-- <p>Find me in app/views/simple_pages/contact.html.erb</p> -->
<p>Email : sudhirjha.gs@gmail.com</p>

app/views/simple_pages/index.html.erb
<h1>Welcome to Online Bike Shop</h1>

<!-- <h1>SimplePages#index</h1> -->
<!-- <p>Find me in app/views/simple_pages/index.html.erb</p> -->
<!-- <p>Welcome! The date and time is <%#= Time.now %></p> -->
<%# test_variable = 42 %>
<%#= test_variable -2 %>

app/views/simple_pages/landing_page.html.erb
<!-- <h1>SimplePages#landing_page</h1>
<p>Find me in app/views/simple_pages/landing_page.html.erb</p> -->

 <!-- <h2>Featured Product:</h2> -->


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <% @products.each do |product| %>
      <div class="carousel-item<%= " active" if product == @products.first %>">
      <!-- <div class="carousel-item"> -->
      <%= image_tag(product.image_url)unless product.image_url.nil? %>
        <div class="carousel-caption d-none d-md-block">
        <%= product.name %>
        </div>
      <!-- </div> -->
    </div>
  <%end%>

  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>